language: node_js
node_js:
- '10'
dist: trusty
sudo: required
before_script:
- npm install -g eslint
- npm install --no-optional
cache:
  directories:
  - node_modules
env:
- NODE_ENV=ci
script:
- sleep 5
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: gie4RkWlLbeRKToDSGTbO4cQQeh1jtTS9ANeJe531D2Q2KYu7VIb4uf0Z+kmVcxFI5G4TBEIfTNPlrUj3HyGtyhr4AFIB5ePiOaO0xcsdHvWywLxdUeBEHJCHlHDT9Pdgg9QDe9MTlJM5z80VWTCmE+LIJyczsXIFfmyA0cmitMXN/1Ngyr/3MNbIb4Keb7mISxkW/ZjdqKoo799BHY44Ft+9zNGIbOMFFVowFwtZF5PoKWZE2CPIhTau86eyFmErubwcPoU93OopT9lSIedcUhGUyxiHzWjZltATdwpEXmSbMkIb3008CY/dB++9m7dZ/U4HdpXMUZGzYgApXM3riiORLDjp3oKVGY1dFQ2RISw99sF0o2l7ShlgCfcHAouQNYHDk7hiGSvBRifGL8HjlPmQ9UgkhH4BsWFZva79oomLwEMhAZDD5+R3zepQsb7Rbxit5XS23gIhBBUhPb+da7XUjBKcrP0VeDxXd/QOs9/1bc0Hh2jNTw8d0S0UhiBKBp2brrI+IUJXT8q1FUr25yPb++oLJcmOOkfUQeBJB6HcIYipq6qg97e2ITeT4/8liWkiK+y7SKU5gNoeTQsEkXsFqt8MJxVxDNTdx4WK5n5nLcJIhU6AEl0wh4XtSGa50iM0H5muvYqZmjSe+DxPExxxt5UY4ytGN6nI7YIUAg=
  app: mailer-scheduler-app
  skip_cleanup: true
